check-leaks: true
v8-stack-trace-limit: 100
color: true
recursive: true
require:
  - 'source-map-support/register'
#   - 'ts-node/register/transpile-only'
full-trace: true
extension:
  - 'ts'

spec: '**/*.test.{js,cjs}'
