version: 2
jobs:
  build:
    docker:
      - image: >-
          circleci/node:8@sha256:0c5f90412d75e91a2438b742ddda127b392be8ec398a460dc3af856386c9fb5d
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package-lock.json" }}'
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package-lock.json" }}'
      - run: npm test
      - run:
          name: Upload code coverage to Codecov
          command: 'bash <(curl -s https://codecov.io/bash)'
